### ISSUE TITLE
Suggestions : use of ndarray crate

### ISSUE THREAD

**Issue by sachaarbonel** [tuvistavie/rust-simple-nn#2]
I was considering implementing a NN to learn rust and  found your repository when searching for existing implementations. I see that your conclusion is rust is too slow for neural networks. Considering that a NN is mostly matrix multiplications, why not optimized it or use an external crate. Have you considered to benchmark [ndarray](https://crates.io/crates/ndarray) ?

**Comment by danhper** [comment]
Hi,
Sorry if the README is not clear. I just rephrased it a little.
I am absolutely not saying that Rust is too slow for neural networks. I am sure that an optimized implementation could compete with C++ based ones.
However, my implementation is mostly for learning purposes and is too slow for production use.
There are, of course, many ways my implementation could be made faster but this is not really the goal of the project.

**Comment by sachaarbonel** [comment]
Thank's for your highlight, very nice project btw ! I'll close this.
